### ISSUE TITLE
F5XC Regional Edge Load Balancer Challenge

### ISSUE THREAD

**Issue by thnguyenf5** [f5devcentral/F5-SE-Outcome-Based-Learning#12]
In the Regional Edge Origin Pool, https://f5-se-outcome-based-learning.readthedocs.io/en/latest/docs/challenges/f5xc-regional-edge-load-balancer/step01.html,
It mentions creating a dual NGINX Application Servers.  I believe it should say 2x JuiceShop Servers from the base environment.

**Comment by jmcalalang** [comment]
that was super confusing. It has been fixed to:

Create an Origin Pool(s) with the public ip addresses of the application servers hosting Juice Shop
