### ISSUE TITLE
F5XC Regional Edge Observability - Delays in the TLS score

### ISSUE THREAD

**Issue by thnguyenf5** [f5devcentral/F5-SE-Outcome-Based-Learning#13]
As part of the lab, there's a section to test TLS score.  Is there a way to trigger a TLS scoring evaluation or does that happen after a certain time interval?

https://f5-se-outcome-based-learning.readthedocs.io/en/latest/docs/challenges/f5xc-regional-edge-observability/step02.html

**Comment by jmcalalang** [comment]
So, the HTTP monitor is what triggers the TLS score, and how often you have scheduled the monitor is how long until the first TLS score will show up. If you set it to once per day, you would need to wait till the next day to see the initial result.
