### ISSUE TITLE
Clarity of DNS domain name

### ISSUE THREAD

**Issue by HoGonzalez1992** [f5devcentral/F5-SE-Outcome-Based-Learning#15]
When reviewing the documentation in Lab1, within the _Securely expose your website with SSL encryption and a DNS name_ section, it states "Use a domain that is already defined within your tenant. do not create a new domain." 

There is a small assumption that one knows that a domain name is already configured and that only a sub domain is necessary to to expose the site as well as where to find it. While an SE may be able to identify this, when provided to a customer it may not be as clear.  

Adding a note to better clarify or point a help point user in the right direction as to where the domain can be identified may be useful.

**Comment by jmcalalang** [comment]
closed with new note added +1 point
